name: AutoNPC
version: '1.0'
main: win.oreo.autonpc.AutoNPC
authors: [oreo (superoreo)]
description: AutoNPC Plugin for mc 1.12.2
website: github.com/superoreoooooo
commands:
  npc:
    aliases:
      - n